### ISSUE TITLE
无法正常建立mysql连接

### ISSUE THREAD

**Issue by yvmouX** [Dogend233/MailBox#3]
[15:45:50 INFO]: [MailBox]: 无本地模块可加载
[15:45:54 WARN]: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[15:45:54 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:895)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:820)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
[15:45:54 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
[15:45:54 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
[15:45:54 WARN]:        at MailBox-v3.3.2.jar//com.tripleying.dogend.mailbox.data.MySQLData.createConnection(MySQLData.java:52)
[15:45:54 WARN]:        at MailBox-v3.3.2.jar//com.tripleying.dogend.mailbox.data.MySQLData.enable(MySQLData.java:41)
[15:45:54 WARN]:        at MailBox-v3.3.2.jar//com.tripleying.dogend.mailbox.manager.DataManager.selectData(DataManager.java:74)
[15:45:54 WARN]:        at MailBox-v3.3.2.jar//com.tripleying.dogend.mailbox.MailBox.lambda$load$0(MailBox.java:116)
[15:45:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:45:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:45:54 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1127)
[15:45:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[15:45:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:45:54 WARN]: Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'mail'@'223.90.176.223' (using password: YES)
[15:45:54 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[15:45:54 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[15:45:54 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[15:45:54 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[15:45:54 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[15:45:54 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
[15:45:54 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:128)
[15:45:54 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:849)
[15:45:54 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:771)
[15:45:54 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:739)
[15:45:54 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:156)
[15:45:54 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:468)
[15:45:54 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:213)
[15:45:54 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1430)
[15:45:54 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:134)
[15:45:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:839)
[15:45:54 WARN]:        ... 15 more
[15:45:54 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.isClosed()" because "this.connection" is null
[15:45:54 WARN]:        at MailBox-v3.3.2.jar//com.tripleying.dogend.mailbox.data.MySQLData.enable(MySQLData.java:42)
[15:45:54 WARN]:        at MailBox-v3.3.2.jar//com.tripleying.dogend.mailbox.manager.DataManager.selectData(DataManager.java:74)
[15:45:54 WARN]:        at MailBox-v3.3.2.jar//com.tripleying.dogend.mailbox.MailBox.lambda$load$0(MailBox.java:116)
[15:45:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:45:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:45:54 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1127)
[15:45:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[15:45:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:45:54 INFO]: [MailBox]: 数据源: mysql 启用失败, 卸载插件
[15:45:54 INFO]: [MailBox] Disabling MailBox v3.3.2

**Comment by Dogend233** [comment]
![Image](https://github.com/user-attachments/assets/4a13fb7d-6335-41e0-b457-e6105706bc5e)
检查一下用户名密码呢
